# Generated by Django 4.0.1 on 2022-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('feed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('item_quantity', models.PositiveSmallIntegerField()),
                ('item_inuse', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('customer_num', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact_num', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('room', models.CharField(max_length=20)),
                ('guest', models.PositiveSmallIntegerField()),
                ('checkin_date', models.CharField(max_length=20)),
                ('checkout_date', models.CharField(max_length=20)),
                ('num_of_days', models.PositiveSmallIntegerField()),
                ('activity', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('room_price', models.PositiveSmallIntegerField()),
                ('room_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('employee_num', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_num', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
